apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    version: master
  name: k8s-app
  namespace: k8s-app-namespace
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-app
  targetCPUUtilizationPercentage: 70