apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-app
  name: k8s-app
  namespace: k8s-app-namespace
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-app
    release: k8s-app
  type: ClusterIP